sudo: false

language: node_js

install: travis_wait 15 mvn install

node_js:
  - 'stable'

services:
  - mongodb

cache:
  directories:
    - 'node_modules'

script:
  - npm run test
  - npm run coveralls

notifications:
  email: false
